Repository shared-solutions/BE, pull requests merged in 2024-02, with the labels that each got.

#45 Docs#42 마이페이지(Q&A질문, Q&A답변) API 수정
  src/main/java/friend/spring/converter/CommentConverter.java
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/repository/CommentRepository.java
  src/main/java/friend/spring/repository/LevelRepository.java
  src/main/java/friend/spring/repository/PostRepository.java
  src/main/java/friend/spring/service/CommentService.java
  src/main/java/friend/spring/service/CommentServiceImpl.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/service/UserService.java
  src/main/java/friend/spring/service/UserServiceImpl.java
  src/main/java/friend/spring/web/controller/UserRestController.java
  src/main/java/friend/spring/web/dto/CommentResponseDTO.java
  src/main/java/friend/spring/web/dto/PostResponseDTO.java
  src/main/java/friend/spring/web/dto/UserResponseDTO.java
Labels: :page_facing_up: Docs

#43 Feat#35 카드 투표 API 구현
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/domain/Card_poll.java
  src/main/java/friend/spring/domain/Gauge_poll.java
  src/main/java/friend/spring/domain/Gauge_vote.java
  src/main/java/friend/spring/domain/General_poll.java
  src/main/java/friend/spring/domain/Point.java
  src/main/java/friend/spring/domain/Post.java
  src/main/java/friend/spring/domain/User.java
  src/main/java/friend/spring/domain/enums/PostType.java
  src/main/java/friend/spring/repository/PointRepository.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/service/VoteServiceImpl.java
  src/main/java/friend/spring/web/controller/PostRestController.java
  src/main/java/friend/spring/web/controller/VoteRestController.java
  src/main/java/friend/spring/web/dto/PostRequestDTO.java
Labels: ✨Feature

#46 [FEAT] 회원가입 구현
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/domain/User.java
  src/main/java/friend/spring/repository/UserRepository.java
  src/main/java/friend/spring/service/UserService.java
  src/main/java/friend/spring/service/UserServiceImpl.java
  src/main/java/friend/spring/web/controller/UserRestController.java
  src/main/java/friend/spring/web/dto/UserRequestDTO.java
  src/main/java/friend/spring/web/dto/UserResponseDTO.java
Labels: ✨Feature

#52 #32 Feat: 댓글 삭제
  src/main/java/friend/spring/domain/Comment.java
  src/main/java/friend/spring/domain/Gauge_vote.java
  src/main/java/friend/spring/service/CommentService.java
  src/main/java/friend/spring/service/CommentServiceImpl.java
  src/main/java/friend/spring/web/controller/CommentRestController.java
Labels: ✨Feature

#50 #42 Refactor : 마이페이지(Q&A질문, Q&A답변) API 수정2차
  src/main/java/friend/spring/converter/UserConverter.java
Labels: :recycle: Refactor

#54 #33 Feat: 글 추천(좋아요) 생성/해제
  src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/repository/PostLikeRepository.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/web/controller/PostRestController.java
  src/main/java/friend/spring/web/dto/PostResponseDTO.java
Labels: ✨Feature

#56 #47 [FEAT} 로그인,JWT 구현
  src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/friend/spring/config/RedisRepositoryConfig.java
  src/main/java/friend/spring/config/WebSecurityConfig.java
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/domain/User.java
  src/main/java/friend/spring/domain/enums/RoleType.java
  src/main/java/friend/spring/security/JwtTokenProvider.java
  src/main/java/friend/spring/service/UserService.java
  src/main/java/friend/spring/service/UserServiceImpl.java
  src/main/java/friend/spring/web/controller/UserRestController.java
  src/main/java/friend/spring/web/dto/TokenDTO.java
  src/main/java/friend/spring/web/dto/UserResponseDTO.java
Labels: ✨Feature

#64 Feat#55 홈 - 고민투표 글 목록 조회
  src/main/java/friend/spring/aws/s3/AmazonS3Manager.java
  src/main/java/friend/spring/config/AmazonConfig.java
  src/main/java/friend/spring/config/S3Config.java
  src/main/java/friend/spring/converter/CandidateConverter.java
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/domain/Post.java
  src/main/java/friend/spring/repository/CandidateRepository.java
  src/main/java/friend/spring/repository/CommentRepository.java
  src/main/java/friend/spring/repository/PostLikeRepository.java
  src/main/java/friend/spring/repository/PostRepository.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/service/S3Service.java
  src/main/java/friend/spring/web/controller/PostRestController.java
  src/main/java/friend/spring/web/controller/S3Controller.java
  src/main/java/friend/spring/web/dto/CandidateResponseDTO.java
  src/main/java/friend/spring/web/dto/PostResponseDTO.java
  src/main/java/friend/spring/web/dto/UserResponseDTO.java
Labels: ✨Feature

#66 Feat#65 로그아웃, 토큰재발급 RequestHeader 추가
  src/main/java/friend/spring/web/controller/PostRestController.java
  src/main/java/friend/spring/web/controller/UserRestController.java
Labels: :recycle: Refactor

#73 Feat#67 Chore: Elasticache Redis로 추가 & Feat: 스크랩 추가/해제 구현
  src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/repository/PostScrapRepository.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/web/controller/PostRestController.java
  src/main/java/friend/spring/web/dto/PostResponseDTO.java
  src/main/resources/application.yml
Labels: ❔Question

#76 #67 Refactor: 로그인 토큰으로 변경해서 적용
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/service/CommentService.java
  src/main/java/friend/spring/service/CommentServiceImpl.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/web/controller/CommentRestController.java
  src/main/java/friend/spring/web/controller/PostRestController.java
Labels: :recycle: Refactor

#81 #80 Refactor: User 관련 기능 swagger 간단 설명 작성
  src/main/java/friend/spring/web/controller/UserRestController.java
Labels: :recycle: Refactor

#82 #80 Refactor: User 관련 기능 swagger 간단 설명 작성
  src/main/java/friend/spring/web/controller/UserRestController.java
Labels: :recycle: Refactor

#79 Feat#23 Refactor: 댓글 좋아요 생성 시 추가 검증
  src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/friend/spring/service/CommentServiceImpl.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/web/controller/CommentRestController.java
  src/main/java/friend/spring/web/controller/PostRestController.java
Labels: :recycle: Refactor

#87 #86 Refactor: 이미지 업로드 방식 수정, 기타 리팩토링(회원가입, 후기글 작성 시 내 투표 보기, 후보 등록)
  .platform/nginx/conf.d/client_max_body_size.conf
  src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/friend/spring/aws/s3/AmazonS3Manager.java
  src/main/java/friend/spring/config/AmazonConfig.java
  src/main/java/friend/spring/converter/CandidateConverter.java
  src/main/java/friend/spring/converter/CommentConverter.java
  src/main/java/friend/spring/converter/FileConverter.java
  src/main/java/friend/spring/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/domain/Candidate.java
  src/main/java/friend/spring/domain/File.java
  src/main/java/friend/spring/domain/Post.java
  src/main/java/friend/spring/domain/User.java
  src/main/java/friend/spring/domain/enums/S3ImageType.java
  src/main/java/friend/spring/repository/FileRepository.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/service/S3Service.java
  src/main/java/friend/spring/service/UserServiceImpl.java
  src/main/java/friend/spring/web/controller/PostRestController.java
  src/main/java/friend/spring/web/controller/S3Controller.java
  src/main/java/friend/spring/web/dto/CandidateResponseDTO.java
  src/main/java/friend/spring/web/dto/FileDTO.java
  src/main/java/friend/spring/web/dto/ParentPostDTO.java
  src/main/java/friend/spring/web/dto/PollOptionDTO.java
  src/main/java/friend/spring/web/dto/PostRequestDTO.java
  src/main/java/friend/spring/web/dto/PostResponseDTO.java
  src/main/java/friend/spring/web/dto/UserRequestDTO.java
  src/main/resources/application.yml
Labels: :recycle: Refactor

#88 #86 Chore: 글 작성 시 파일 첨부 null인 경우 처리
  src/main/java/friend/spring/service/PostServiceImpl.java
Labels: :recycle: Refactor

#90 #86 Chore: 게시글 상세 보기 사진 가져오는 방식 수정
  src/main/java/friend/spring/converter/PostConverter.java
Labels: :recycle: Refactor

#91 #29 Refactor: 댓글 조회 시 상태 추가
  src/main/java/friend/spring/converter/CommentConverter.java
  src/main/java/friend/spring/web/dto/CommentResponseDTO.java
Labels: :recycle: Refactor

#92 #29 Refactor: Cors 설정(WebMvcConfigurer)
  src/main/java/friend/spring/config/CorsConfig.java
Labels: :bug: Bug

#94 #29 Refactor: Cors 설정 변경(2)
  src/main/java/friend/spring/config/CorsConfig.java
Labels: :recycle: Refactor

#97 Feat#71 토큰 유효 시간 수정
  src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/friend/spring/security/JwtTokenProvider.java
Labels: :recycle: Refactor

#98 #33 Refactor: 글 좋아요/스크랩 중복 불가능하도록 설정
  src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/friend/spring/service/PostServiceImpl.java
Labels: :recycle: Refactor

#99 #30 Refactor: 댓글 채택 포인트 관련 내용 추가 및 글/댓글 소속 일치 여부 확인 추가
  src/main/java/friend/spring/service/CommentServiceImpl.java
Labels: :recycle: Refactor

#100 Feat#29 Refactor: 댓글 조회 page 처리 제거
  src/main/java/friend/spring/repository/CommentRepository.java
  src/main/java/friend/spring/service/CommentService.java
  src/main/java/friend/spring/service/CommentServiceImpl.java
  src/main/java/friend/spring/web/controller/CommentRestController.java
Labels: :recycle: Refactor

#111 #108 Refactor: 댓글 조회 시 좋아요/글 주인/내가 쓴 댓글 여부 추가 & 댓글 삭제 api url에서 like 제거
  src/main/java/friend/spring/converter/CommentConverter.java
  src/main/java/friend/spring/service/CommentService.java
  src/main/java/friend/spring/service/CommentServiceImpl.java
  src/main/java/friend/spring/web/controller/CommentRestController.java
  src/main/java/friend/spring/web/dto/CommentResponseDTO.java
Labels: :recycle: Refactor

#112 #108 Refactor: 대댓글 목록 수정
  src/main/java/friend/spring/service/CommentServiceImpl.java
Labels: :recycle: Refactor

#114 #113 Refactor: 유저 프로필 사진 이미 있는 경우 수정으로 변경
  src/main/java/friend/spring/domain/File.java
  src/main/java/friend/spring/repository/FileRepository.java
  src/main/java/friend/spring/service/MyPageServiceImpl.java
  src/main/java/friend/spring/service/S3Service.java
  src/main/java/friend/spring/web/controller/MyPageRestController.java
Labels: :recycle: Refactor

#119 Feat#71 카카오 로그인 구현
  build.gradle
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/kakao/controller/AuthController.java
  src/main/java/friend/spring/kakao/converter/AuthConverter.java
  src/main/java/friend/spring/kakao/domain/enums/SocialType.java
  src/main/java/friend/spring/kakao/dto/response/KakaoProfile.java
  src/main/java/friend/spring/kakao/dto/response/OAuthToken.java
  src/main/java/friend/spring/kakao/provider/KakaoAuthProvider.java
  src/main/java/friend/spring/kakao/service/AuthService.java
  src/main/java/friend/spring/kakao/service/AuthServiceImpl.java
  src/main/java/friend/spring/repository/UserRepository.java
  src/main/java/friend/spring/security/JwtTokenProvider.java
  src/main/java/friend/spring/service/UserServiceImpl.java
  src/main/java/friend/spring/web/dto/TokenDTO.java
  src/main/java/friend/spring/web/dto/UserResponseDTO.java
  src/main/resources/application.yml
Labels: ✨Feature

#125 #113 Refactor: 가장 핫한 고민투표 임시로 7일 이내로 수정
  src/main/java/friend/spring/repository/PostRepository.java
Labels: :recycle: Refactor

#126 #113 Refactor: 홈 고민글 리스트에서 후보 이미지, 게이지 값 추가
  src/main/java/friend/spring/converter/CandidateConverter.java
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/web/dto/CandidateResponseDTO.java
  src/main/java/friend/spring/web/dto/PostResponseDTO.java
Labels: :recycle: Refactor

#129 비밀번호 재설정 메일인증 API
  src/main/java/friend/spring/service/EmailService.java
  src/main/java/friend/spring/service/PasswordEmailService.java
  src/main/java/friend/spring/web/controller/UserRestController.java
  src/main/java/friend/spring/web/dto/UserRequestDTO.java
Labels: ✨Feature

#132 REFACTOR(불필요한 파일 축소, 수정)
  src/main/java/friend/spring/OAuth/provider/KakaoAuthProvider.java
  src/main/java/friend/spring/service/EmailService.java
  src/main/java/friend/spring/service/PasswordEmailService.java
  src/main/java/friend/spring/web/controller/UserRestController.java
  src/main/java/friend/spring/web/dto/UserRequestDTO.java
Labels: :recycle: Refactor

#140 #113 Refactor: 알림 타입 변경
  src/main/java/friend/spring/converter/SseConverter.java
Labels: :recycle: Refactor

#141 #113 Refactor: 홈 - 안 읽은 알림 존재 여부 조회 설명 수정
  src/main/java/friend/spring/web/controller/AlarmRestController.java
Labels: :recycle: Refactor

#145 #113 Refactor: 알림 리스트 조회에서 read도 반환
  src/main/java/friend/spring/converter/AlarmConverter.java
  src/main/java/friend/spring/web/dto/AlarmResponseDTO.java
Labels: :recycle: Refactor

#148 #147 Refactor: 글 상세보기 시 후보 아이디도 반환으로 수정
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/web/dto/PollOptionDTO.java
Labels: :recycle: Refactor

#153 #147 Refactor: 댓글 상세보기 대댓글 관련 수정
  src/main/java/friend/spring/service/CommentServiceImpl.java
Labels: :recycle: Refactor

#154 #146 Refactor: 홈 - 답변을 기다리는 고민들 / 홈 - 지금 가장 핫한 고민투표 리턴 값 수정
  src/main/java/friend/spring/converter/CandidateConverter.java
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/repository/PostRepository.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/web/controller/PostRestController.java
  src/main/java/friend/spring/web/dto/CandidateResponseDTO.java
  src/main/java/friend/spring/web/dto/PostResponseDTO.java
Labels: :recycle: Refactor

#156 #155 Refactor: 댓글 조회 시 채택 여부도 리턴
  src/main/java/friend/spring/converter/CommentConverter.java
  src/main/java/friend/spring/repository/CommentChoiceRepository.java
  src/main/java/friend/spring/service/CommentServiceImpl.java
  src/main/java/friend/spring/web/dto/CommentResponseDTO.java
Labels: :recycle: Refactor

#157 #155 Refactor: 투표/글 작성 시 포인트 amount 값 수정
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/service/VoteServiceImpl.java
Labels: :recycle: Refactor

#158 [REFACTOR] 비밀번호 재설정 완료, accessToken 시간 수정
  src/main/java/friend/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/security/JwtTokenProvider.java
  src/main/java/friend/spring/service/EmailService.java
  src/main/java/friend/spring/service/UserService.java
  src/main/java/friend/spring/service/UserServiceImpl.java
  src/main/java/friend/spring/web/controller/UserRestController.java
  src/main/java/friend/spring/web/dto/UserRequestDTO.java
  src/main/java/friend/spring/web/dto/UserResponseDTO.java
Labels: :recycle: Refactor

#160 #155 Refactor: 일반/카드 투표 allCandidatePercent 리스트 리턴으로 수정
  src/main/java/friend/spring/converter/PostConverter.java
  src/main/java/friend/spring/repository/CommentRepository.java
  src/main/java/friend/spring/service/SchedulerService2.java
Labels: :recycle: Refactor

#161 #155 Refactor: 이미지 파일 업로드 방식 MultipartFile -> Base64로 수정
  src/main/java/friend/spring/converter/Base64Decoder.java
  src/main/java/friend/spring/service/PostService.java
  src/main/java/friend/spring/service/PostServiceImpl.java
  src/main/java/friend/spring/service/S3Service.java
  src/main/java/friend/spring/web/controller/PostRestController.java
  src/main/java/friend/spring/web/dto/CandidateRequestDTO.java
  src/main/java/friend/spring/web/dto/PostRequestDTO.java
Labels: :recycle: Refactor

#162 #155 Refactor: 글 작성에서 MULTIPART_FORM_DATA_VALUE 제거
  src/main/java/friend/spring/web/controller/PostRestController.java
Labels: :recycle: Refactor

#163 #155 Refactor: 글 작성에서 MULTIPART_FORM_DATA_VALUE 추가
  src/main/java/friend/spring/web/controller/PostRestController.java
Labels: :recycle: Refactor

#167 #155 Refactor: Nginx 설정 proxy_read_timeout 값 1시간으로 수정 (테스트)
  .platform/nginx.conf
Labels: :recycle: Refactor

#168 #155 Refactor: Nginx 설정 proxy_connet, send timeout 값 1시간으로 수정 (테스트)
  .platform/nginx.conf
Labels: :recycle: Refactor

#169 #155 Refactor: Nginx 설정 connection 추가
  .platform/nginx.conf
Labels: :recycle: Refactor

#171 #155 Refactor: nginx.conf 위치 변경
  .platform/nginx/nginx.conf
Labels: :recycle: Refactor

#172 #155 Refactor: nginx 설정에서 timeout 설정만 남기고 제거 (테스트)
  .platform/nginx/nginx.conf
Labels: :recycle: Refactor

#173 #155 Refactor: cors 설정에서 allowedOriginPatterns("*") 제거해보기 (테스트)
  src/main/java/friend/spring/config/CorsConfig.java
Labels: :recycle: Refactor

#174 #155 Refactor: Nginx 설정 proxy timeout 설정 제거
  .platform/nginx/nginx.conf
Labels: :recycle: Refactor

#175 #155 Refactor: cors 설정에서 allowedOriginPatterns("*") 다시 추가
  src/main/java/friend/spring/config/CorsConfig.java
Labels: :recycle: Refactor

#176 #155 Refactor: cors 설정에서 .allowedOrigins("*") 제거 (테스트)
  src/main/java/friend/spring/config/CorsConfig.java
Labels: :recycle: Refactor

#177 #155 Refactor: nginx.conf에서 cors 설정 제거 (테스트)
  .platform/nginx/nginx.conf
Labels: :recycle: Refactor

#179 Feat#155 Refactor: nginx.conf cors 설정 추가, Access-Control-Allow-Credential 'true' 추가
  .platform/nginx/nginx.conf
  src/main/java/friend/spring/config/CorsConfig.java
Labels: :recycle: Refactor

#180 #155 Refactor: nginx.conf cors 설정 제거, CorsConfig에 .allowCredentials(true) 추가
  src/main/java/friend/spring/config/CorsConfig.java
Labels: :recycle: Refactor

#181 #155 Refactor: nginx.conf cors 설정 제거, CorsConfig에 .allowCredentials(true) 추가
  .platform/nginx/nginx.conf
Labels: :recycle: Refactor

#184 [REFACTOR] 비밀번호 재설정 리턴값 수정
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/domain/User.java
  src/main/java/friend/spring/service/UserService.java
  src/main/java/friend/spring/service/UserServiceImpl.java
  src/main/java/friend/spring/web/controller/UserRestController.java
  src/main/java/friend/spring/web/dto/UserRequestDTO.java
  src/main/resources/application.yml
Labels: :recycle: Refactor
