Repository shared-solutions/BE, pull requests merged in 2024-01, with the labels that each got.

#11 Feat#5 CI/CD 구축
  .ebextensions-dev/00-makefiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  .platform/nginx/conf.d/client_max_body_size.conf
  Procfile
  build.gradle
Labels: ✨Feature, ⚒️ CI/CD

#12 #5 Chore: health check 추가
  src/main/java/friend/spring/web/controller/RootController.java
Labels: ✨Feature, ⚒️ CI/CD

#13 #5 Chore: application.yml 환경변수 설정 및 gitignore 수정
  .gitignore
  src/main/resources/application.yml
Labels: ⚒️ CI/CD

#14 #5 Chore: 임시 수정
  README.md
Labels: ⚒️ CI/CD

#15 #8 Chore: CompileJava 오류 수정 - build.gradle, Builder
  build.gradle
  src/main/java/friend/spring/domain/Comment.java
  src/main/java/friend/spring/domain/Gauge_question.java
  src/main/java/friend/spring/domain/General_question.java
  src/main/java/friend/spring/domain/Level.java
  src/main/java/friend/spring/domain/Post.java
  src/main/java/friend/spring/domain/User.java
Labels: :recycle: Refactor

#16 Feat#8 리전 수정
  .github/workflows/dev_deploy.yml
  README.md
Labels: ⚒️ CI/CD

#20 #8 Chore: application.yml cloud 위치 수정
  src/main/java/friend/spring/service/S3Service.java
  src/main/java/friend/spring/web/controller/S3Controller.java
  src/main/resources/application.yml
Labels: :recycle: Refactor

#21 #8 Chore: S3 업로드 시 ContentType 지정
  build.gradle
  src/main/java/friend/spring/aws/s3/AmazonS3Manager.java
  src/main/java/friend/spring/config/S3Config.java
Labels: :recycle: Refactor

#24 Feat#19
  src/main/java/friend/spring/converter/UserConverter.java
  src/main/java/friend/spring/service/UserService.java
  src/main/java/friend/spring/service/UserServiceImpl.java
  src/main/java/friend/spring/web/controller/UserRestController.java
  src/main/java/friend/spring/web/dto/UserRequestDTO.java
  src/main/java/friend/spring/web/dto/UserResponseDTO.java
Labels: ✨Feature

#26 #1 Feat: 댓글 작성
  src/main/java/friend/spring/converter/CommentConverter.java
  src/main/java/friend/spring/domain/User.java
  src/main/java/friend/spring/repository/CommentRepository.java
  src/main/java/friend/spring/service/CommentService.java
  src/main/java/friend/spring/service/CommentServiceImpl.java
  src/main/java/friend/spring/web/controller/CommentRestController.java
  src/main/java/friend/spring/web/dto/CommentRequestDTO.java
  src/main/java/friend/spring/web/dto/CommentResponseDTO.java
Labels: ✨Feature
